export const moreColumns = [
  { Header: 'ID', accessor: 'id' },
  { Header: 'Nombre', accessor: 'nombre' },
  { Header: 'Apellido', accessor: 'apellido' },
  { Header: 'Edad', accessor: 'edad' },
  { Header: 'País', accessor: 'pais' },
  { Header: 'Ciudad', accessor: 'ciudad' },
  { Header: 'Email', accessor: 'email' },
  { Header: 'Teléfono', accessor: 'telefono' },
  { Header: 'Profesión', accessor: 'profesion' },
  { Header: 'Compañía', accessor: 'compania' },
  { Header: 'Departamento', accessor: 'departamento' },
  { Header: 'Años de Experiencia', accessor: 'experiencia' },
  { Header: 'Estado Civil', accessor: 'estado_civil' },
  { Header: 'Salario Anual', accessor: 'salario' },
  { Header: 'Fecha de Ingreso', accessor: 'fecha_ingreso' },
];

export const moreData = [
  {
    id: 1,
    nombre: 'Juan',
    apellido: 'Pérez',
    edad: 30,
    pais: 'Argentina',
    ciudad: 'Buenos Aires',
    email: 'juan.perez@example.com',
    telefono: '+54 11 1234 5678',
    profesion: 'Ingeniero de Software',
    compania: 'Tech Solutions',
    departamento: 'IT',
    experiencia: 8,
    estado_civil: 'Soltero',
    salario: 55000,
    fecha_ingreso: '2016-05-12',
  },
  {
    id: 2,
    nombre: 'Ana',
    apellido: 'González',
    edad: 25,
    pais: 'México',
    ciudad: 'Ciudad de México',
    email: 'ana.gonzalez@example.com',
    telefono: '+52 55 2345 6789',
    profesion: 'Diseñadora Gráfica',
    compania: 'Creative Agency',
    departamento: 'Diseño',
    experiencia: 5,
    estado_civil: 'Casada',
    salario: 42000,
    fecha_ingreso: '2018-07-23',
  },
  {
    id: 3,
    nombre: 'Luis',
    apellido: 'Martínez',
    edad: 40,
    pais: 'Colombia',
    ciudad: 'Bogotá',
    email: 'luis.martinez@example.com',
    telefono: '+57 1 3456 7890',
    profesion: 'Gerente de Ventas',
    compania: 'Global Corp',
    departamento: 'Ventas',
    experiencia: 15,
    estado_civil: 'Casado',
    salario: 70000,
    fecha_ingreso: '2010-03-15',
  },
  {
    id: 4,
    nombre: 'Sofía',
    apellido: 'López',
    edad: 28,
    pais: 'Chile',
    ciudad: 'Santiago',
    email: 'sofia.lopez@example.com',
    telefono: '+56 2 4567 8901',
    profesion: 'Marketing Manager',
    compania: 'StartUp Chile',
    departamento: 'Marketing',
    experiencia: 6,
    estado_civil: 'Soltera',
    salario: 48000,
    fecha_ingreso: '2017-11-30',
  },
  {
    id: 5,
    nombre: 'Carlos',
    apellido: 'Ramírez',
    edad: 35,
    pais: 'Perú',
    ciudad: 'Lima',
    email: 'carlos.ramirez@example.com',
    telefono: '+51 1 5678 9012',
    profesion: 'Analista Financiero',
    compania: 'Banco de Perú',
    departamento: 'Finanzas',
    experiencia: 12,
    estado_civil: 'Casado',
    salario: 65000,
    fecha_ingreso: '2013-09-10',
  },
  {
    id: 6,
    nombre: 'Marta',
    apellido: 'Vargas',
    edad: 32,
    pais: 'España',
    ciudad: 'Madrid',
    email: 'marta.vargas@example.com',
    telefono: '+34 91 345 6789',
    profesion: 'Abogada',
    compania: 'Bufete Legal',
    departamento: 'Legal',
    experiencia: 10,
    estado_civil: 'Divorciada',
    salario: 60000,
    fecha_ingreso: '2015-04-12',
  },
  {
    id: 7,
    nombre: 'Roberto',
    apellido: 'Jiménez',
    edad: 29,
    pais: 'Chile',
    ciudad: 'Valparaíso',
    email: 'roberto.jimenez@example.com',
    telefono: '+56 32 567 8901',
    profesion: 'Ingeniero Civil',
    compania: 'Constructora Chile',
    departamento: 'Ingeniería',
    experiencia: 7,
    estado_civil: 'Soltero',
    salario: 53000,
    fecha_ingreso: '2017-06-08',
  },
  {
    id: 8,
    nombre: 'Lucía',
    apellido: 'Sánchez',
    edad: 26,
    pais: 'Argentina',
    ciudad: 'Córdoba',
    email: 'lucia.sanchez@example.com',
    telefono: '+54 351 123 4567',
    profesion: 'Contadora',
    compania: 'Consultores Financieros',
    departamento: 'Finanzas',
    experiencia: 4,
    estado_civil: 'Soltera',
    salario: 47000,
    fecha_ingreso: '2019-02-14',
  },
  {
    id: 9,
    nombre: 'Daniel',
    apellido: 'Torres',
    edad: 38,
    pais: 'México',
    ciudad: 'Guadalajara',
    email: 'daniel.torres@example.com',
    telefono: '+52 33 1234 5678',
    profesion: 'Desarrollador Web',
    compania: 'Tech Devs',
    departamento: 'IT',
    experiencia: 12,
    estado_civil: 'Casado',
    salario: 62000,
    fecha_ingreso: '2012-09-18',
  },
  {
    id: 10,
    nombre: 'Camila',
    apellido: 'Mendoza',
    edad: 24,
    pais: 'Uruguay',
    ciudad: 'Punta del Este',
    email: 'camila.mendoza@example.com',
    telefono: '+598 42 234 5678',
    profesion: 'Diseñadora UX',
    compania: 'Creative Minds',
    departamento: 'Diseño',
    experiencia: 3,
    estado_civil: 'Soltera',
    salario: 45000,
    fecha_ingreso: '2020-10-05',
  },
  {
    id: 11,
    nombre: 'Gabriel',
    apellido: 'Morales',
    edad: 45,
    pais: 'Colombia',
    ciudad: 'Medellín',
    email: 'gabriel.morales@example.com',
    telefono: '+57 4 345 6789',
    profesion: 'Analista de Datos',
    compania: 'Data Solutions',
    departamento: 'Analítica',
    experiencia: 22,
    estado_civil: 'Casado',
    salario: 72000,
    fecha_ingreso: '2003-08-20',
  },
  {
    id: 12,
    nombre: 'Patricia',
    apellido: 'Ortega',
    edad: 34,
    pais: 'México',
    ciudad: 'Monterrey',
    email: 'patricia.ortega@example.com',
    telefono: '+52 81 1234 5678',
    profesion: 'Psicóloga',
    compania: 'Bienestar Humano',
    departamento: 'Recursos Humanos',
    experiencia: 10,
    estado_civil: 'Divorciada',
    salario: 58000,
    fecha_ingreso: '2014-11-05',
  },
  {
    id: 13,
    nombre: 'Esteban',
    apellido: 'Ríos',
    edad: 31,
    pais: 'Perú',
    ciudad: 'Cusco',
    email: 'esteban.rios@example.com',
    telefono: '+51 84 567 8901',
    profesion: 'Consultor',
    compania: 'Consultoría Estratégica',
    departamento: 'Consultoría',
    experiencia: 9,
    estado_civil: 'Soltero',
    salario: 54000,
    fecha_ingreso: '2016-01-20',
  },
  {
    id: 14,
    nombre: 'Paola',
    apellido: 'Ruiz',
    edad: 27,
    pais: 'Chile',
    ciudad: 'Concepción',
    email: 'paola.ruiz@example.com',
    telefono: '+56 41 234 5678',
    profesion: 'Analista de Negocios',
    compania: 'Corporación Global',
    departamento: 'Negocios',
    experiencia: 5,
    estado_civil: 'Casada',
    salario: 50000,
    fecha_ingreso: '2018-04-12',
  },
  {
    id: 15,
    nombre: 'Ignacio',
    apellido: 'Hernández',
    edad: 50,
    pais: 'Venezuela',
    ciudad: 'Caracas',
    email: 'ignacio.hernandez@example.com',
    telefono: '+58 212 345 6789',
    profesion: 'CEO',
    compania: 'Hernández Consulting',
    departamento: 'Dirección',
    experiencia: 25,
    estado_civil: 'Casado',
    salario: 120000,
    fecha_ingreso: '1999-02-01',
  },
  {
    id: 16,
    nombre: 'Verónica',
    apellido: 'Cabrera',
    edad: 42,
    pais: 'Argentina',
    ciudad: 'Rosario',
    email: 'veronica.cabrera@example.com',
    telefono: '+54 341 234 5678',
    profesion: 'Directora de Marketing',
    compania: 'Innovación SA',
    departamento: 'Marketing',
    experiencia: 20,
    estado_civil: 'Casada',
    salario: 90000,
    fecha_ingreso: '2004-06-23',
  },
  {
    id: 17,
    nombre: 'Andrés',
    apellido: 'Navarro',
    edad: 37,
    pais: 'Colombia',
    ciudad: 'Cali',
    email: 'andres.navarro@example.com',
    telefono: '+57 2 456 7890',
    profesion: 'Consultor IT',
    compania: 'IT Advisors',
    departamento: 'Consultoría',
    experiencia: 14,
    estado_civil: 'Soltero',
    salario: 67000,
    fecha_ingreso: '2009-12-18',
  },
  {
    id: 18,
    nombre: 'Rosa',
    apellido: 'Pérez',
    edad: 33,
    pais: 'México',
    ciudad: 'Querétaro',
    email: 'rosa.perez@example.com',
    telefono: '+52 442 234 5678',
    profesion: 'Ingeniera de Sistemas',
    compania: 'Sistemas Globales',
    departamento: 'IT',
    experiencia: 9,
    estado_civil: 'Casada',
    salario: 59000,
    fecha_ingreso: '2015-05-05',
  },
  {
    id: 19,
    nombre: 'Jorge',
    apellido: 'Fernández',
    edad: 41,
    pais: 'Chile',
    ciudad: 'Temuco',
    email: 'jorge.fernandez@example.com',
    telefono: '+56 45 234 5678',
    profesion: 'Project Manager',
    compania: 'Construcciones Limitada',
    departamento: 'Proyectos',
    experiencia: 18,
    estado_civil: 'Divorciado',
    salario: 75000,
    fecha_ingreso: '2006-07-12',
  },
  {
    id: 20,
    nombre: 'Natalia',
    apellido: 'Figueroa',
    edad: 36,
    pais: 'Uruguay',
    ciudad: 'Salto',
    email: 'natalia.figueroa@example.com',
    telefono: '+598 473 456 789',
    profesion: 'Asesora Legal',
    compania: 'Legales Internacionales',
    departamento: 'Legal',
    experiencia: 13,
    estado_civil: 'Casada',
    salario: 68000,
    fecha_ingreso: '2010-09-15',
  },
  {
    id: 21,
    nombre: 'Fernanda',
    apellido: 'Rojas',
    edad: 45,
    pais: 'Uruguay',
    ciudad: 'Montevideo',
    email: 'fernanda.rojas@example.com',
    telefono: '+598 2 7890 1234',
    profesion: 'Arquitecta',
    compania: 'Constructora S.A.',
    departamento: 'Arquitectura',
    experiencia: 20,
    estado_civil: 'Casada',
    salario: 80000,
    fecha_ingreso: '2005-02-18',
  },
];
